values:
   description: "Validator Configuration File"
   version: 0.9
   rule_statuses:
      - value: 'TESTING'
      - value: 'RELEASED'
      - value: 'DEPRECATED'
   sharing_classifications:
      - value: 'TLP:CLEAR|TLP:CLEAR//COMMERCIAL|TLP:WHITE|TLP:WHITE//COMMERCIAL'
      - value: 'TLP:GREEN|TLP:GREEN//COMMERCIAL'
      - value: 'TLP:AMBER|TLP:AMBER//COMMERCIAL'
      - value: 'TLP:AMBER\+STRICT|TLP:AMBER\+STRICT//COMMERCIAL'
   category_types:
      - value: 'INFO'
      - value: 'EXPLOIT'
      - value: 'TECHNIQUE'
      - value: 'TOOL'
      - value: 'MALWARE'
   malware_types:
      - value: "ADWARE"
      - value: "APT"
      - value: "BACKDOOR"
      - value: "BANKER"
      - value: "BOOTKIT"
      - value: "BOT"
      - value: "BROWSER-HIJACKER"
      - value: "BRUTEFORCER"
      - value: "CLICKFRAUD"
      - value: "CRYPTOMINER"
      - value: "DDOS"
      - value: "DOWNLOADER"
      - value: "DROPPER"
      - value: "EXPLOITKIT"
      - value: "FAKEAV"
      - value: "HACKTOOL"
      - value: "INFOSTEALER"
      - value: "KEYLOGGER"
      - value: "LOADER"
      - value: "OBFUSCATOR"
      - value: "POS"
      - value: "PROXY"
      - value: "RAT"
      - value: "RANSOMWARE"
      - value: "ROOTKIT"
      - value: "SCANNER"
      - value: "SCAREWARE"
      - value: "SPAMMER"
      - value: "TROJAN"
      - value: "VIRUS"
      - value: "WIPER"
      - value: "WEBSHELL"
      - value: "WORM"
   actor_types:
      - value: "APT"
      - value: "CRIMEWARE"
      - value: "FIN"
   hash_types:
      - value: "[a-fA-F0-9]{32}"
      - value: "[a-fA-F0-9]{40}"
      - value: "[a-fA-F0-9]{64}"
   unvalidated_regex:
      - value: ".*"
   universal_regex:
      - value: '[^a-z]*'

id:
   description: "Autogenerated unique identifier based on RFC 4122 UUID"
   format: "Base 62 conversion of UUID"
   unique: Yes
   optional: Optional
   validator: valid_uuid

fingerprint:
   description: "SHA256 hash of string values and condition"
   format: "hex string"
   unique: Yes
   optional: Optional
   validator: valid_fingerprint

version:
   description: "Revision of the rule, autogenerated as 1.0"
   format: "x.x"
   unique: Yes
   optional: Optional
   validator: valid_version

score:
   description: "Percentage of confidence in the rule"
   format: integer
   unique: Yes
   optional: Yes
   validator: valid_percentage

minimum_yara:
   description: "Minimum version of Yara to run the rule"
   format: "x.x"
   unique: Yes
   optional: Yes
   validator: valid_version

date:
   description: "Date stamp of when the rule was created"
   format: "YYYY-MM-DD"
   unique: Yes
   optional: Yes
   validator: valid_date

modified:
   description: "Last modified date"
   format: "YYYY-MM-DD"
   unique: Yes
   optional: Optional
   validator: valid_date

tags:
   description: "A set of keywords relevant to the rule"
   format: unvalidated
   unique: No
   optional: Yes
   validator: None

status:
   description: "Status of the rule as assigned by the submitter"
   format: "uppercase"
   unique: Yes
   optional: No
   validator: valid_regex
   argument:
      valueName: rule_statuses

sharing:
   description: "Sharing limitation"
   format: "uppercase"
   unique: Yes
   optional: No
   validator: valid_regex
   argument:
      valueName: sharing_classifications

source:
   description: "Source organization of the YARA rule"
   format: "uppercase"
   unique: Yes
   optional: No
   validator: valid_source

author:
   description: "Author and organization"
   format: "lowercase_author@uppercase_organization"
   unique: No
   optional: No
   validator: valid_regex
   argument:
      regexExpression: ^[a-zA-Z]+\@[A-Z]+$|^[A-Z\s._-]+$|^.*$

description:
   description: "The description of the rule"
   format: ".*"
   unique: Yes
   optional: No
   validator: valid_regex
   argument:
      regexExpression: ".*"

category:
   description: "Detection category"
   format: "uppercase"
   unique: Yes
   optional: No
   validator: valid_category
   argument:
      child: info|exploit|technique|tool|malware

info|exploit|technique|tool|malware:
   description: "Specific information about the category"
   format: "uppercase"
   unique: No
   optional: Yes
   validator: valid_category_type
   argument:
      parent: category
      generate_mitre_att_from: ^tool$|^malware$

malware_type:
   description: "Indication of the malware capability/purpose"
   format: "uppercase"
   unique: No
   optional: Yes
   validator: valid_regex
   argument:
      valueName: malware_types

mitre_att:
   description: "Valid MITRE ATT&CK ID codes"
   format: "'TA####'|'T####'|'M####'|'G####'|'S####'"
   unique: No
   optional: Yes
   validator: valid_mitre_att

actor_type:
   description: "The type of the actor"
   format: "uppercase"
   unique: 2
   optional: Yes
   validator: valid_regex
   argument:
      valueName: actor_types

actor:
   description: "Actor name as stated by the source"
   format: "uppercase"
   unique: Yes
   optional: Yes
   validator: valid_actor
   argument:
      child: mitre_group
      required: actor_type

mitre_group:
   description: 'Autogenerated alias of the actor value'
   format: "uppercase"
   unique: Yes
   optional: Yes
   validator: mitre_group_generator
   argument:
      parent: actor

report:
   description: "Report linked to this rule"
   format: ".*"
   unique: No
   optional: Yes
   validator: valid_regex
   argument:
      valueName: universal_regex

reference:
   description: "Reference for the rule"
   format: "unvalidated"
   unique: No
   optional: Yes
   validator: valid_regex
   argument:
      valueName: unvalidated_regex

hash:
   description: "Sample hash"
   format: "lowercase MD5, SHA, or SHA-256"
   unique: No
   optional: Yes
   validator: valid_regex
   argument:
      valueName: hash_types

vol_script:
   description: "Reverse Engineering team usage"
   format: "unvalidated"
   unique: Yes
   optional: Yes
   validator: None

al_*:
   description: "Assembly Line specific metadata"
   format: "unvalidated"
   unique: Yes
   optional: Yes
   validator: None

credit:
   description: "Author credit metadata"
   format: "unvalidated"
   unique: No
   optional: Yes
   validator: None

original_*:
   description: "Preserve original metadata from converted rules"
   format: "unvalidated"
   unique: No
   optional: Yes
   validator: None
